// Generated by gen-meta.js
const appName = 'Pisdeo';

const isProd = false;
const appVersion = '0.0.2';
const appVersionFull = '0.0.2-40548b8-b202207021205';
const compileTime = '2022/07/02 12:05:57';
const commitHash = '40548b8';

export {
    isProd, appVersion, appVersionFull, compileTime, commitHash
};
