version: '1.0'
name: build_nwd
displayName: build nwd
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-5064318e
    displayName: build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./dist && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: nwd
        deployArtifact:
          - source: build
            name: nwd
            target: ~/gitee_go/nwd
            dependArtifact: BUILD_ARTIFACT
        script: ''
        dependsOn: build_nodejs
permissions:
  - role: admin
    members: []
