name: Build
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: |
          yarn
          
      - name: Build
        run: |
          yarn build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          
